import { blockBounds, roadCoord } from "./constants";
import type { MissionDef, NpcProfile, Place } from "./types";

export const CITY_NAME = "潮港都市";

export const PLACES: Place[] = [
  { id: "centralAve", name: "中央大道", x: roadCoord(3), z: 0, radius: 28 },
  { id: "bay", name: "海灣區", x: 0, z: blockBounds(2, 0).cz - 8, radius: 36 },
  { id: "park", name: "新生公園", x: blockBounds(1, 1).cx, z: blockBounds(1, 1).cz, radius: 22 },
  { id: "eastBiz", name: "東城商業區", x: blockBounds(4, 2).cx, z: blockBounds(4, 2).cz, radius: 26 },
  { id: "westInd", name: "西港工業區", x: blockBounds(0, 2).cx, z: blockBounds(0, 2).cz, radius: 26 },
  { id: "station", name: "中央車站", x: blockBounds(2, 2).cx, z: blockBounds(2, 2).cz, radius: 18 },
  { id: "police", name: "城南警察局", x: blockBounds(2, 4).cx, z: blockBounds(2, 4).cz, radius: 18 },
  { id: "parking", name: "港灣停車場", x: blockBounds(4, 3).cx, z: blockBounds(4, 3).cz, radius: 16 },
  { id: "shop", name: "東城便利商店", x: blockBounds(4, 2).cx + 6, z: blockBounds(4, 2).cz - 8, radius: 10 },
];

export function placeById(id: Place["id"]): Place {
  const p = PLACES.find((x) => x.id === id);
  if (!p) throw new Error(`missing place ${id}`);
  return p;
}

export const NPC_PROFILES: NpcProfile[] = [
  {
    id: "chen",
    name: "陳志豪",
    job: "計程車司機",
    personality: "健談、急性子",
    status: "準備下班",
    shirt: 0xf0c040,
    pants: 0x2a2e36,
    hair: 0x1a120c,
  },
  {
    id: "lin",
    name: "林雅婷",
    job: "咖啡店員",
    personality: "溫柔、觀察力強",
    status: "休息中",
    shirt: 0xd8c4b0,
    pants: 0x3e2a22,
    hair: 0x3a2214,
  },
  {
    id: "wang",
    name: "王大偉",
    job: "巡警",
    personality: "正經、不苟言笑",
    status: "巡邏中",
    shirt: 0x2d4a74,
    pants: 0x1c2430,
    hair: 0x111111,
  },
  {
    id: "huang",
    name: "黃淑芬",
    job: "會計師",
    personality: "謹慎、講效率",
    status: "趕著開會",
    shirt: 0x4a5a6a,
    pants: 0x222830,
    hair: 0x2b1a12,
  },
  {
    id: "chang",
    name: "張偉傑",
    job: "大學生",
    personality: "好奇、愛吐槽",
    status: "晃來晃去",
    shirt: 0x3aa0c8,
    pants: 0x3c4654,
    hair: 0x1c1410,
  },
  {
    id: "wu",
    name: "吳佳蓉",
    job: "護理師",
    personality: "沉穩、關心人",
    status: "剛下班",
    shirt: 0xe8eef2,
    pants: 0x5aa0b4,
    hair: 0x24160e,
  },
  {
    id: "lee",
    name: "李國強",
    job: "水電工",
    personality: "直球、熱心",
    status: "找工具行",
    shirt: 0xc45a2a,
    pants: 0x3a3328,
    hair: 0x2a2018,
  },
  {
    id: "chou",
    name: "周子涵",
    job: "平面設計師",
    personality: "慢熱、嘴毒",
    status: "找靈感",
    shirt: 0x5a3a58,
    pants: 0x1e1e24,
    hair: 0x0e0e12,
  },
  {
    id: "hsu",
    name: "許明輝",
    job: "夜市攤販",
    personality: "豪爽、愛開玩笑",
    status: "進貨途中",
    shirt: 0xd24a4a,
    pants: 0x2c2c30,
    hair: 0x1a1a1a,
  },
  {
    id: "tsai",
    name: "蔡依靜",
    job: "律師",
    personality: "冷靜、用字精準",
    status: "散步思考案情",
    shirt: 0x1c1c22,
    pants: 0x2a2a32,
    hair: 0x16120e,
  },
  {
    id: "passenger",
    name: "鄭浩然",
    job: "夜班工程師",
    personality: "疲憊、話少",
    status: "等車回家",
    shirt: 0x3d5c4a,
    pants: 0x242428,
    hair: 0x1a1612,
  },
];

export const MISSIONS: MissionDef[] = [
  {
    id: "intro",
    title: "城市初體驗",
    brief: "先搞到一台車，再開去中央車站熟悉路況。",
    reward: 1500,
    steps: [
      {
        id: "get-car",
        objective: "取得一台車輛",
        hint: "靠近路邊車輛後按 E 上車",
      },
      {
        id: "to-station",
        objective: "駕駛前往中央車站",
        hint: "跟著小地圖上的目標標記前進",
      },
    ],
  },
  {
    id: "night-fare",
    title: "午夜載客",
    brief: "去新生公園接一名乘客，再把他送到東城商業區。",
    reward: 3200,
    steps: [
      {
        id: "pickup",
        objective: "前往新生公園接送乘客",
        hint: "開到公園入口，靠近乘客後按 E 或 F",
      },
      {
        id: "dropoff",
        objective: "將乘客送往東城商業區",
        hint: "載客時請盡量避免嚴重車禍",
      },
    ],
  },
  {
    id: "escape",
    title: "逃出生天",
    brief: "你已被通緝兩星。甩掉警車並解除通緝。",
    reward: 5000,
    steps: [
      {
        id: "lose-cops",
        objective: "躲避警方並解除通緝",
        hint: "拉開距離後找地方躲藏，通緝會逐漸下降",
      },
    ],
  },
];

export const UI = {
  title: "潮港都市",
  tagline: "海灣邊上的低密度都市沙盒",
  play: "開始遊戲",
  resume: "繼續遊戲",
  pause: "暫停",
  how: "操作說明",
  back: "返回",
  missions: "任務",
  shopTitle: "東城便利商店",
  shopClosed: "目前沒有可購買的物品。",
  buyHeal: "能量飲料　回復生命　$200",
  buyRepair: "簡易修車包　修復車輛　$500",
  boughtHeal: "你喝下能量飲料，感覺好多了。",
  boughtRepair: "車輛已大致修復。",
  noMoney: "現金不足。",
  noCar: "你現在沒有可修復的車輛。",
  healthFull: "生命值已滿。",
  carFull: "車輛耐久度已滿。",
  close: "關閉",
  health: "生命值",
  cash: "現金",
  wanted: "通緝",
  speed: "時速",
  durability: "車輛耐久度",
  mission: "目前任務",
  objective: "目標",
  location: "所在位置",
  promptEnter: "按 E 進入車輛",
  promptExit: "按 E 下車",
  promptTalk: "按 F 與市民交談",
  promptShop: "按 E 進入商店",
  promptPickup: "按 E 讓乘客上車",
  wantedUp: (n: number) => `通緝等級提升至 ${n} 星`,
  wantedStart: "你已被警方通緝！",
  wantedSearch: "警方正在搜索你……",
  wantedClear: "你已成功擺脫警方。",
  missionComplete: (title: string, reward: number) =>
    `任務完成：${title}　獲得 $${reward.toLocaleString("zh-TW")}`,
  allMissions: "所有任務已完成。城市仍開放探索。",
  paused: "遊戲暫停",
  howBody: [
    "第三人稱視角　點擊畫面鎖定游標後即可轉動鏡頭，也可按住滑鼠拖曳",
    "WASD　步行移動／駕駛",
    "Shift　跑步",
    "空白鍵　步行時跳躍；駕車時手煞車",
    "C　向後看",
    "滾輪　拉近或拉遠鏡頭",
    "E　互動、上車、下車",
    "F　與市民交談",
    "Esc　暫停",
    "造成嚴重車禍或衝撞路人會提升通緝等級，警車會追捕你。拉開距離並躲藏即可解除通緝。",
  ],
  tutorial: [
    "歡迎來到潮港都市。WASD 走動，滑鼠轉動視角，滾輪縮放鏡頭。",
    "前方路邊有車輛。靠近後按 E 上車。駕車時鏡頭會跟著車頭，空白鍵為手煞車，C 向後看。",
  ],
  nextDialogue: "繼續",
  endDialogue: "結束對話",
  controlsHintFoot: "WASD 移動　Shift 跑　空白 跳　C 回看　滾輪 縮放　E 互動　F 交談",
  controlsHintCar: "W 加速　S 煞車／倒車　A／D 轉向　空白 手煞　C 回看　E 下車",
  lookHint: "點擊畫面鎖定游標以轉動鏡頭",
  touchJump: "跳",
  touchRun: "跑",
  touchBrake: "手煞",
  touchLookBack: "回看",
  touchUse: "E",
  touchTalk: "F",
  touchLook: "視角",
} as const;
